export const IMAGES = {
  quality: require('../assets/images/quality/quality.png'),
  Forward: require('../assets/images/Forward/Forward.png'),
  Reverse: require('../assets/images/Reverse/Reverse.png'),
  Play: require('../assets/images/play/play.png'),
  Pause: require('../assets/images/pause/pause.png'),
  appBackgroundImage: require('../assets/images/appBackgroundImage.png'),
  settingIcon: require('../assets/images/settingIcon/settingIcon.png'),
  playBackSpeedIcon: require('../assets/images/playBackSpeedIcon/playBackSpeedIcon.png'),
  checked: require('../assets/images/checked.png'),
  dowloaded: require('../assets/images/download.png'),
  rightArrow: require('../assets/images/rightArrow/rightArrow.png'),
  back: require('../assets/images/playerImage/back.png'),
  bottomVignette: require('../assets/images/playerImage/bottom-vignette.png'),
  errorIcon: require('../assets/images/playerImage/error-icon.png'),
  expand: require('../assets/images/playerImage/expand.png'),
  loaderIcon: require('../assets/images/playerImage/loader-icon.png'),
  pauseIcon: require('../assets/images/playerImage/pause.png'),
  playIcon: require('../assets/images/playerImage/play.png'),
  shrinkIcon: require('../assets/images/playerImage/shrink.png'),
  topVignette: require('../assets/images/playerImage/top-vignette.png'),
  volume: require('../assets/images/playerImage/volume.png'),
  SubtitleIcon: require('../assets/images/SubtitleIcon/SubtitleIcon.png'),
  SubtitleDisableIcon: require('../assets/images/SubtitleDisableIcon/SubtitleDisableIcon.png'),
};
